### ISSUE TITLE
Need to deal card randomly

### ISSUE THREAD

**Issue by huynq55** [uoftcprg/pokerkit#10]
Thanks for great library!
I want to deal card randomly but can't find the API.

**Comment by AussieSeaweed** [comment]
When you call ``State.deal_board()``, ``State.deal_hole()``, ``State.burn_card()`` without any argument, or just automate them by using relevant automation, the cards that are dealt (either to board, hole, or burn) will be automatically "drawn" (i.e. "deque.popleft"ed) from the deck.

"[During initialization], the state automatically shuffles [the deck] so the cards can be dealt at random when required." In other words, ``State.deck_cards`` from which the dealt cards are drawn are already randomly shuffled during state's initialization when you draw from it.
