### ISSUE TITLE
Option to allow unnecessary folds

### ISSUE THREAD

**Issue by nediamond** [uoftcprg/pokerkit#12]
Hi, first of all this project is awesome and really great for the python (and poker) ecosystem.

I'm trying to use it as an engine for a consumer game and am noticing that it prevents unnecessary folds in a way that is not configurable or overrideable without deep knowledge of the codebase internals. 

Specifically, I think there should be some sort of class option to bypass [this check](https://github.com/uoftcprg/pokerkit/blob/main/pokerkit/state.py#L4283) in `verify_folding` as in casual human games there are edge cases where a person may genuinely want to make the apparently irrational decision to do so, which I intended to allow.
```
if self.bets[player_index] >= max(self.bets):
            raise ValueError('There is no reason for this player to fold.')
```

**Comment by nediamond** [comment]
another couple of features that may be useful would be:
- ability to import/export game states from/to disk 
- start a new game state from a completed one

**Comment by AussieSeaweed** [comment]
Thank you for your kind words!

- As for the situation of folding without facing any bet, the [2023 WSOP Tournament Rules](https://github.com/uoftcprg/pokerkit/blob/main/docs/_static/2023-WSOP-Tournament-Rules.pdf) calls it a "Non-Standard Fold" in Rule 84 which "may be subject to penalty". Plus, PokerStars does not allow unnecessary folds. On top of that, I feel that allowing non-standard folds just confuses some users. With that said, maybe I will allow it. I will think about this.

- There is a built-in way to save and load hand histories. Please read: https://pokerkit.readthedocs.io/en/latest/

- A method to start a new game state from a completed one is a very good idea. I will make it a method in a game class inside https://github.com/uoftcprg/pokerkit/blob/main/pokerkit/games.py.

Good luck with whatever you are working on.

**Comment by nediamond** [comment]
@AussieSeaweed I wouldn't even necessarily advocate for allowing the "Non-Standard Fold" by default in any mode - just some sort of option so the behavior is controllable, but your reasoning makes sense thanks. Will also check out the hand history feature set!
