### ISSUE TITLE
Can i simulate old-school classic plain 5-card draw poker game with pokerkit?

### ISSUE THREAD

**Issue by grzesw** [uoftcprg/pokerkit#14]
i would love to see some example setup in docs

**Comment by AussieSeaweed** [comment]
Yes, you can. PokerKit is designed so users can define their own games. For no-limit 5-card single-draw, please create a class that inherits from [``NoLimitDeuceToSevenLowballSingleDraw``](https://github.com/uoftcprg/pokerkit/blob/main/pokerkit/games.py#L1665) and override the class variable ``hand_types`` so it equals ``(StandardHighHand,)``.

```Python
class NoLimitFiveCardDraw(NoLimitDeuceToSevenLowballSingleDraw):
    hand_types = (StandardHighHand,)
```

Unfortunately, I am overseas, and I cannot test this. Please play around with it.
