### ISSUE TITLE
How to Get Player Statistics like VPIP, PFR etc.?

### ISSUE THREAD

**Issue by john911f** [uoftcprg/pokerkit#17]
Thank you for the wonderful repo!

I was wondering are there any helper functions/methods to output player histories like VPIP, PFR, similar to the other statistical methods like these:

```
from pokerkit import *

hh0 = ...
hh1 = ...
hh2 = ...
...

ss = Statistics.from_hand_history(hh0, hh1, hh2, ...)

print(ss['John Smith'].vpip)
print(ss['John Smith'].pfr)
```

**Comment by AussieSeaweed** [comment]
Sorry, there is not. I thought about adding them but didn't get around to it.
