### ISSUE TITLE
Is it possible to see the distribution of the winning hand types from 'calculate_hand_strength'? 

### ISSUE THREAD

**Issue by jabber39** [uoftcprg/pokerkit#20]
Hi everyone, is it possible to see the distribution of hand types when the hand wins from 'calculate_hand_strength'? Eg when the hand won, 10% of the time it was a flush, 20% it was a full house etc.

 `from concurrent.futures import ProcessPoolExecutor
from pokerkit import *
with ProcessPoolExecutor() as executor:
    print(calculate_hand_strength(
        3,
        parse_range('AdJdQhJs'),
        Card.parse('6d7d6h'),
        4,
        5,
        Deck.STANDARD,
        (pk.hands.OmahaHoldemHand,),
        sample_count=100_00,
        executor=executor,
    ))`

**Comment by AussieSeaweed** [comment]
No, not at this time, but that would be a very good addition.

**Comment by AussieSeaweed** [comment]
I'm quite sure you can modify the existing code to accomplish this.

**Comment by jabber39** [comment]
@AussieSeaweed thank you so much for the info! Do you all accept pushes if I were to work on it?
Also is there a better way for me to ask questions instead of just pushing issues? 
Thank you all for this great library and I really appreciate the info and responses

**Comment by AussieSeaweed** [comment]
Thank you for your kind words! Creating issues for questions is completely fine. Also, I will be happy to take a look if you do make a push.

**Comment by AussieSeaweed** [comment]
I think a good solution is to allow callers to pass a callback function as an argument which will be called at the end of each simulation. You can use it to generate your distribution.
