### ISSUE TITLE
Dataset in this repository

### ISSUE THREAD

**Issue by zzzjoey** [uoftcprg/pokerkit#6]
Thanks for your excellent open-source work!
I notice that there are wsop and pluribus hand history in the data folder. How can I browse or use these files? 
Thank you for your reply.

**Comment by AussieSeaweed** [comment]
Hi, thank you for your interest!

For now, please take a look at the "Tooling" section of the [PHH File Format Specification](https://doi.org/10.48550/arXiv.2312.11753) for example usages. It explains how to parse the files and go through each action using the PokerKit package.

There is no easy way to visualize the states though. You will have to print the values you are interested in to stdout or write a GUI for it.

I plan on overhauling the documentation to comprehensively include all the features of PokerKit, when I have the time. Also, I am thinking of making a tool named ``felt`` to visualize poker games, but that is a work in progress.
