### ISSUE TITLE
Awesome library! 

### ISSUE THREAD

**Issue by keithorange** [uoftcprg/pokerkit#8]
No issue here - just a comment!
Randomly stumbled upon this repo! I am UofT alum! Also played at the poker club! Very cool to see these packages! You guys should make a GTO poker solver like GTOWizard.com since thats like 250$ per month and would be useful for students!

**Comment by AussieSeaweed** [comment]
Thanks for your kind words! We might have met before. I was one of the leads of the club for 3 years. As for building a solver... maybe, if I feel like it.
